config {
    type: "incremental", 
    schema: "RAW",
    tags: ["sqlserver", "calendario"]
}
SELECT 
    SYS_CHANGE_VERSION,	
    SYS_CHANGE_OPERATION,	
    SYS_CHANGE_CREATION_VERSION,	
    COMMIT_TIME,
    CT_DAT_CRONOLOGICA,
    DAT_CRONOLOGICA,
    _PARTITIONTIME AS PARTITIONTIME
FROM `LAND.calendario_data_cronologica`

${ when(incremental(), `WHERE _PARTITIONTIME > (SELECT MAX(PARTITIONTIME) FROM ${self()})`) }