config {
    type: "incremental",
    schema: "RAW",
    tags: ["sqlserver", "comercial"]
}
SELECT 
    SYS_CHANGE_VERSION,	
    SYS_CHANGE_OPERATION,	
    SYS_CHANGE_CREATION_VERSION,	
    COMMIT_TIME,
    CT_COD_TIPO_MARCA_SORTIMENTO,
    COD_TIPO_MARCA_SORTIMENTO,
	NOM_TIPO_MARCA_SORTIMENTO,
    _PARTITIONTIME AS PARTITIONTIME
FROM `LAND.comercial_tipo_marca_sortimento_cev`

${ when(incremental(), `WHERE _PARTITIONTIME > (SELECT MAX(PARTITIONTIME) FROM ${self()})`) }