config {
    type: "incremental",
    schema: "RAW",
    tags: ["sqlserver", "corp"]
}
SELECT 
    SYS_CHANGE_VERSION,	
    SYS_CHANGE_OPERATION,	
    SYS_CHANGE_CREATION_VERSION,	
    COMMIT_TIME,
    CT_NUM_NIVEL_HIERARQUIA,	
    NUM_NIVEL_HIERARQUIA,
	NOM_NIVEL_HIERARQUIA,
    _PARTITIONTIME AS PARTITIONTIME
FROM `LAND.corp_nivel_hierarquia_produto_cev`

${ when(incremental(), `WHERE _PARTITIONTIME > (SELECT MAX(PARTITIONTIME) FROM ${self()})`) }