config {
    type: "incremental",
    schema: "RAW",
    tags: ["sqlserver", "corp"]
}
SELECT 
    SYS_CHANGE_VERSION,	
    SYS_CHANGE_OPERATION,	
    SYS_CHANGE_CREATION_VERSION,	
    COMMIT_TIME,
    CT_COD_MOTIVO,	
    COD_MOTIVO,
	NOM_MOTIVO,
	IND_USO_LOGISTICA,
	IND_USO_PRICING,
	IND_USO_COMPRAS,
    _PARTITIONTIME AS PARTITIONTIME
FROM `LAND.corp_motivo_nao_distribuicao_cev`

${ when(incremental(), `WHERE _PARTITIONTIME > (SELECT MAX(PARTITIONTIME) FROM ${self()})`) }