config {
    type: "incremental",
    schema: "RAW",
    tags: ["sqlserver", "corp"]
}
SELECT 
    SYS_CHANGE_VERSION,	
    SYS_CHANGE_OPERATION,	
    SYS_CHANGE_CREATION_VERSION,	
    COMMIT_TIME,
    CT_FAIXA_CORTE,
    FAIXA_CORTE,
    CUSTO_INICIAL,
    CUSTO_FINAL,
    ETQ_LIMITE,
    _PARTITIONTIME AS PARTITIONTIME
FROM `LAND.corp_alocar_classe_custo_lb`

${ when(incremental(), `WHERE _PARTITIONTIME > (SELECT MAX(PARTITIONTIME) FROM ${self()})`) }