config {
    type: "incremental",
    schema: "RAW",
    tags: ["sqlserver", "corp"]
}
SELECT 
    SYS_CHANGE_VERSION,	
    SYS_CHANGE_OPERATION,	
    SYS_CHANGE_CREATION_VERSION,	
    COMMIT_TIME,
    CT_COD_CANAL_VENDA,
    COD_CANAL_VENDA,
	NOM_CANAL_VENDA,
    _PARTITIONTIME AS PARTITIONTIME
FROM `LAND.corp_canal_venda_cev`

${ when(incremental(), `WHERE _PARTITIONTIME > (SELECT MAX(PARTITIONTIME) FROM ${self()})`) }