config {
    type: "incremental",
    schema: "RAW",
    tags: ["sqlserver", "corp"]
}
SELECT 
    SYS_CHANGE_VERSION,	
    SYS_CHANGE_OPERATION,	
    SYS_CHANGE_CREATION_VERSION,	
    COMMIT_TIME,
    CT_COD_CLASSE,	
    COD_CLASSE,
	NOM_CLASSE,
    _PARTITIONTIME AS PARTITIONTIME
FROM `LAND.corp_tipo_classe_produto_cev`

${ when(incremental(), `WHERE _PARTITIONTIME > (SELECT MAX(PARTITIONTIME) FROM ${self()})`) }