config {
    type: "incremental",
    schema: "RAW",
    tags: ["sqlserver", "corp"]
}
SELECT 
    SYS_CHANGE_VERSION,	
    SYS_CHANGE_OPERATION,	
    SYS_CHANGE_CREATION_VERSION,	
    COMMIT_TIME,
    CT_COD_GRUPO,	
    COD_GRUPO,
    NOM_GRUPO,
    NOM_TERMO_PESQUISA,
    _PARTITIONTIME AS PARTITIONTIME
FROM `LAND.corp_grupo_fornecedor_cev`

${ when(incremental(), `WHERE _PARTITIONTIME > (SELECT MAX(PARTITIONTIME) FROM ${self()})`) }