config {
    type: "incremental",
    schema: "RAW",
    tags: ["sqlserver", "corp"]
}
SELECT 
    SYS_CHANGE_VERSION,	
    SYS_CHANGE_OPERATION,	
    SYS_CHANGE_CREATION_VERSION,	
    COMMIT_TIME,
    CT_COD_FUNCAO_SUBSTITUTA,	
    COD_FUNCAO_SUBSTITUTA,
    COD_FUNCAO,
    _PARTITIONTIME AS PARTITIONTIME
FROM `LAND.corp_funcao_substituta_cev`

${ when(incremental(), `WHERE _PARTITIONTIME > (SELECT MAX(PARTITIONTIME) FROM ${self()})`) }