config {
    type: "incremental",
    schema: "RAW",
    tags: ["sqlserver", "corp"]
}
SELECT 
    SYS_CHANGE_VERSION,	
    SYS_CHANGE_OPERATION,	
    SYS_CHANGE_CREATION_VERSION,	
    COMMIT_TIME,
    CT_COD_GRUPO_COMPARATIVO_META,	
    COD_GRUPO_COMPARATIVO_META,
	NOM_GRUPO_COMPARATIVO_META,
    _PARTITIONTIME AS PARTITIONTIME
FROM `LAND.corp_grupo_comparativo_meta_filial_cev`

${ when(incremental(), `WHERE _PARTITIONTIME > (SELECT MAX(PARTITIONTIME) FROM ${self()})`) }