config {
    type: "incremental",
    schema: "RAW",
    tags: ["sqlserver", "corp"]
}
SELECT 
    SYS_CHANGE_VERSION,	
    SYS_CHANGE_OPERATION,	
    SYS_CHANGE_CREATION_VERSION,	
    COMMIT_TIME,
    CT_COD_TIPO_FILIAL,	
    COD_TIPO_FILIAL,
	NOM_TIPO_FILIAL,
	IND_META_VENDA,
	IND_ESTOQUE_FISICO,
    _PARTITIONTIME AS PARTITIONTIME
FROM `LAND.corp_tipo_filial_cev`

${ when(incremental(), `WHERE _PARTITIONTIME > (SELECT MAX(PARTITIONTIME) FROM ${self()})`) }