config {
    type: "incremental",
    schema: "RAW",
    tags: ["oracle", "msaf"]
}
SELECT 
    SYS_CHANGE_VERSION,	
    SYS_CHANGE_OPERATION,	
    SYS_CHANGE_CREATION_VERSION,	
    COMMIT_TIME,
    COD_CATEGORIA,
    DSC_CATEGORIA,
    _PARTITIONTIME AS PARTITIONTIME
FROM `LAND.msaf_categoria_cev`

${ when(incremental(), `WHERE _PARTITIONTIME > (SELECT MAX(PARTITIONTIME) FROM ${self()})`) }