config {
    type: "incremental",
    schema: "RAW",
    tags: ["postgresql"]
}
SELECT 
    SYS_CHANGE_VERSION,	
    SYS_CHANGE_OPERATION,	
    SYS_CHANGE_CREATION_VERSION,	
    COMMIT_TIME,	
    CT_id,
    id,
	insurance_id,
	order_id,
	name,
	price,
	total_price,
	discount,
	discount_name,
	_PARTITIONTIME AS PARTITIONTIME
FROM `LAND.oms_order_insurance_cev`

${ when(incremental(), `WHERE _PARTITIONTIME > (SELECT MAX(PARTITIONTIME) FROM ${self()})`) }