config {
	type: "incremental", 
	schema: "RAW",
	tags: ["postgresql"] 
}
SELECT 
	SYS_CHANGE_VERSION,	
	SYS_CHANGE_OPERATION, 
	SYS_CHANGE_CREATION_VERSION, 
	COMMIT_TIME, 
	CT_id, 
	id,
	order_id,
	status_id,
	issue_id,
	issue_sequence,
	creation_date,
	user_id,
	system_name,
	details,
	rightnow_id,
	_PARTITIONTIME AS PARTITIONTIME
FROM `LAND.oms_order_issue_lb`

${ when(incremental(), `WHERE _PARTITIONTIME > (SELECT MAX(PARTITIONTIME) FROM ${self()})`) }