config {
    type: "incremental",
    schema: "RAW",
    tags: ["sqlserver", "plancom"]
}
SELECT 
    SYS_CHANGE_VERSION,	
    SYS_CHANGE_OPERATION,	
    SYS_CHANGE_CREATION_VERSION,	
    COMMIT_TIME,
    CT_COD_CATEGORIA,
    COD_CATEGORIA,
	NOM_CATEGORIA_COMPLETO,
	NOM_GM,
	NOM_GC,
    _PARTITIONTIME AS PARTITIONTIME
FROM `LAND.plancom_depara_organograma_lb`

${ when(incremental(), `WHERE _PARTITIONTIME > (SELECT MAX(PARTITIONTIME) FROM ${self()})`) }