config {
    type: "incremental",
    schema: "RAW",
    tags: ["sqlserver", "plancom"]
}
SELECT 
    SYS_CHANGE_VERSION,	
    SYS_CHANGE_OPERATION,	
    SYS_CHANGE_CREATION_VERSION,	
    COMMIT_TIME,
    CT_COD_FORN_SAP,	
    COD_FORN_SAP,
    BANDEIRA,
    NOM_FORNECEDOR,
    NOM_GRUPO,
    _PARTITIONTIME AS PARTITIONTIME
FROM `LAND.plancom_fornecedor_cvlb`

${ when(incremental(), `WHERE _PARTITIONTIME > (SELECT MAX(PARTITIONTIME) FROM ${self()})`) }